import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/app/Header";
import Footer from "@/app/Footer";
import {Suspense} from "react";
import Loading from "@/app/loading";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className='container mx-auto bg-slate-700 text-slate-50'>
            <div className='flex flex-col min-h-screen'>
                <main className='flex-grow'>
                    <Header />
                    <Suspense fallback={<Loading />}>
                        {children}
                    </Suspense>
                </main>
            </div>
            <Footer />
        </body>
        </html>
    );
}
